name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'build')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: actions/build-push-action@v6
        with:
          build-args: |
            http_proxy=${{ vars.HTTP_PROXY }}
            https_proxy=${{ vars.HTTPS_PROXY }}
          load: true
          context: .
          file: ./Dockerfile
          tags: ${{ gitea.repository }}:latest

      - name: Inspect
        run: |
          echo "Inspecting Docker image..."
          docker inspect ${{ gitea.repository }}:latest
          echo "Docker image inspection completed."